services:
  backend:
    build: ../backend
    container_name: simon-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
      - shared_assets:/app/shared_assets

  frontend:
    build: ../frontend
    container_name: simon-frontend
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - shared_assets:/app/public/user_images
      - /app/node_modules


  nginx:
    image: nginx:latest
    container_name: simon-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

# Define the shared volume at the top level
volumes:
  shared_assets: