services:
  backend:
    build: ../backend
    container_name: simon-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=simon-access-key
      - MINIO_SECRET_KEY=simon-secret-key
      - DATABASE_URL=mysql+mysqlclient://sikerang_simontpi:SX2HMdAB5SahnuyXUyg7@localhost:3306/sikerang_simontpi

  frontend:
    build: ../frontend
    container_name: simon-frontend
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules


  nginx:
    image: nginx:latest
    container_name: simon-nginx
    ports:
      - "80:80"
      - "9002:9002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
      - minio

  # Add the new MinIO service
  minio:
    image: minio/minio:latest
    container_name: simon-minio
    command: server /data --console-address ":9001"

    environment:
      - MINIO_ROOT_USER=simon-access-key
      - MINIO_ROOT_PASSWORD=simon-secret-key
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9002 # ALSO UPDATE THIS LINE
    volumes:
      - ./minio_data:/data # Persist MinIO data locally
